name: Portainer Ping to Auto Deploy

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    if: contains(github.event.head_commit.message, '[deploy]')
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request to Portainer Webhook
        run: |
          curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }}
